language: python
python:
  - '2.7'

os:
  - linux
#  - osx

branches:
  only:
    - master

before_install:
  - pip install coveralls

install: true

script:
  - make dist
  - make test
  - coveralls
  
